
[workspace]
name = "positionsys"
version = "0.1.0"
description = "framework with singulary position system for algo trading (trading bots)"
authors = ["dxdye <s-tbertr@haw-landshut.de>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]


[dependencies]
python = ">=3.13.7,<3.14"
pytest = "==8.4.1"
requests = "==2.32.4"
ruff = ">=0.12.12,<0.13"
pylint = ">=3.3.8,<4"
pytest-bdd = ">=7.3.0,<8"
jsonschema = ">=4.25.1,<5"
alpaca-py = ">=0.43.2,<0.44"
pdoc = ">=16.0.0,<17"
git = ">=2.52.0,<3"

[tool.pixi.scripts]
test = "pytest -s"

[tool.pixi.tasks.test]
cmd = "pytest -s"
help = "Run the test suite using pytest."

[tasks]
lint = "pylint src"
fmt = "ruff format && ruff check"

test = { cmd = "pytest -s", cwd = "src/tests/" }
"test::data" = { cmd = "pytest -s -q test_data.py && pytest -v ", cwd = "src/tests/" }
"test::sma_bot" = { cmd = "pytest -s test_sma_bot.py", cwd = "src/tests/", env = { PYTHONPATH = "./" } }
"test::position" = { cmd = "pytest -s test_position.py", cwd = "src/tests/", env = { PYTHONPATH = "./" } }

[tasks.docs]
cmd = "pdoc src"
env = { PYTHONPATH = "./src" }

[tasks."docs:saved"]
cmd = "pdoc src -o docs"
env = { PYTHONPATH = "./src" }


