
[workspace]
name = "positionsys"
version = "0.1.0"
description = "framework with singulary position system for algo trading (trading bots)"
authors = ["dxdye <s-tbertr@haw-landshut.de>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]


[dependencies]
python = ">=3.13.7,<3.14"
pytest = "==8.4.1"
requests = "==2.32.4"
ruff = ">=0.12.12,<0.13"
pylint = ">=3.3.8,<4"
pytest-bdd = ">=7.3.0,<8"
sphinx = ">=8.3.0,<9"
sphinx-autodoc-typehints = ">=3.2.0,<4"
jsonschema = ">=4.25.1,<5"

[tool.pixi.scripts]
test = "pytest -s"

[tool.pixi.tasks.test]
cmd = "pytest -s"
help = "Run the test suite using pytest."

[tasks]
lint = "pylint src"
fmt = "ruff format && ruff check"
gendoc = { cmd = "sphinx-build -b html docs/ docs/_build/html" }
"test::data" = { cmd = "pytest -s -q test_data.py && pytest -v ", cwd = "src/tests/" }
test = { cmd = "pytest -s", cwd = "src/tests/" }

